# Proxy configuration
proxy:
  coll: qa-test
  ca_name: pywb HTTPS Proxy CA
  ca_file_cache: ./proxy-certs/pywb-ca.pem
  use_banner: false
  enable_banner: false # More recent syntax for upcoming versions
  enable_content_rewrite: false

# enable memento
enable_memento: true

# Disable replay frame to avoid any gap at the top of the page
framed_replay: false
