version: '2'

services:

  pywb:
    image: webrecorder/pywb
    container_name: pywb
    ports:
      - "8080:8080"
    volumes:
      - ./webarchive:/webarchive
    networks:
      - pywb-puppet

networks:
  pywb-puppet:
    driver: bridge
